import shutil
import tempfile
import unittest
from pathlib import Path

from BetterExport.export_sorter import process_exports


class ExportSorterTests(unittest.TestCase):
    def setUp(self):
        self.temp_dir = Path(tempfile.mkdtemp(prefix="better-export-tests-"))
        self.input_dir = self.temp_dir / "input"
        self.output_dir = self.temp_dir / "output"
        self.input_dir.mkdir()
        self.output_dir.mkdir()

    def tearDown(self):
        shutil.rmtree(self.temp_dir)

    def test_obj_mtllib_reference_tracks_normalized_mtl_name(self):
        obj_name = "SwitchHeadboardHolder v11_SwitchHeadboardHolder v12_Screw_1_Body1.obj"
        mtl_name = "SwitchHeadboardHolder v11_SwitchHeadboardHolder v12_Screw_1_Body1.mtl"

        (self.input_dir / obj_name).write_text(
            "# WaveFront *.obj file (generated by Autodesk ATF)\n\n"
            "mtllib SwitchHeadboardHolder v11_SwitchHeadboardHolder v12_Screw_1_Body1.mtl\n\n"
            "g Body1\n",
            encoding="utf-8"
        )
        (self.input_dir / mtl_name).write_text("newmtl Default\n", encoding="utf-8")

        process_exports(str(self.input_dir), str(self.output_dir))

        normalized_obj = self.output_dir / "SwitchHeadboardHolder" / "OBJs" / "SwitchHeadboardHolder_SwitchHeadboardHolder_Screw_1_Body1.obj"
        normalized_mtl = self.output_dir / "SwitchHeadboardHolder" / "OBJs" / "SwitchHeadboardHolder_SwitchHeadboardHolder_Screw_1_Body1.mtl"

        self.assertTrue(normalized_obj.exists())
        self.assertTrue(normalized_mtl.exists())

        obj_text = normalized_obj.read_text(encoding="utf-8")
        self.assertIn(
            "mtllib SwitchHeadboardHolder_SwitchHeadboardHolder_Screw_1_Body1.mtl",
            obj_text
        )


if __name__ == "__main__":
    unittest.main()
