import shutil
import tempfile
import unittest
from pathlib import Path

from BetterExport.export_sorter import process_exports, scan_export_conflicts


class ExportSorterTests(unittest.TestCase):
    def setUp(self):
        self.temp_dir = Path(tempfile.mkdtemp(prefix="better-export-tests-"))
        self.input_dir = self.temp_dir / "input"
        self.output_dir = self.temp_dir / "output"
        self.input_dir.mkdir()
        self.output_dir.mkdir()

    def tearDown(self):
        shutil.rmtree(self.temp_dir)

    def test_obj_mtllib_reference_tracks_normalized_mtl_name(self):
        obj_name = "SwitchHeadboardHolder v11_SwitchHeadboardHolder v12_Screw_1_Body1.obj"
        mtl_name = "SwitchHeadboardHolder v11_SwitchHeadboardHolder v12_Screw_1_Body1.mtl"

        (self.input_dir / obj_name).write_text(
            "# WaveFront *.obj file (generated by Autodesk ATF)\n\n"
            "mtllib SwitchHeadboardHolder v11_SwitchHeadboardHolder v12_Screw_1_Body1.mtl\n\n"
            "g Body1\n",
            encoding="utf-8"
        )
        (self.input_dir / mtl_name).write_text("newmtl Default\n", encoding="utf-8")

        process_exports(str(self.input_dir), str(self.output_dir))

        normalized_obj = self.output_dir / "SwitchHeadboardHolder" / "OBJs" / "SwitchHeadboardHolder_SwitchHeadboardHolder_Screw_1_Body1.obj"
        normalized_mtl = self.output_dir / "SwitchHeadboardHolder" / "OBJs" / "SwitchHeadboardHolder_SwitchHeadboardHolder_Screw_1_Body1.mtl"

        self.assertTrue(normalized_obj.exists())
        self.assertTrue(normalized_mtl.exists())

        obj_text = normalized_obj.read_text(encoding="utf-8")
        self.assertIn(
            "mtllib SwitchHeadboardHolder_SwitchHeadboardHolder_Screw_1_Body1.mtl",
            obj_text
        )

    def test_conflict_overwrite_replaces_existing_destination(self):
        (self.input_dir / "DeskClip v2.stl").write_text("new-stl", encoding="utf-8")

        existing = self.output_dir / "DeskClip" / "STLs" / "DeskClip.stl"
        existing.parent.mkdir(parents=True, exist_ok=True)
        existing.write_text("old-stl", encoding="utf-8")

        def resolver(source, target, operation, keep_both_target):
            self.assertEqual(operation, "move")
            return "overwrite"

        result = process_exports(str(self.input_dir), str(self.output_dir), allow_overwrite=False, conflict_resolver=resolver)

        self.assertEqual(result["conflicts_overwritten"], 1)
        self.assertEqual(existing.read_text(encoding="utf-8"), "new-stl")

    def test_conflict_keep_both_preserves_versioned_name(self):
        (self.input_dir / "DeskClip v2.stl").write_text("new-stl", encoding="utf-8")

        existing = self.output_dir / "DeskClip" / "STLs" / "DeskClip.stl"
        existing.parent.mkdir(parents=True, exist_ok=True)
        existing.write_text("old-stl", encoding="utf-8")

        result = process_exports(
            str(self.input_dir),
            str(self.output_dir),
            allow_overwrite=False,
            conflict_resolver=lambda source, target, operation, keep_both_target: "keep_both"
        )

        kept_both = self.output_dir / "DeskClip" / "STLs" / "DeskClip v2.stl"
        self.assertEqual(result["conflicts_kept_both"], 1)
        self.assertTrue(existing.exists())
        self.assertTrue(kept_both.exists())
        self.assertEqual(kept_both.read_text(encoding="utf-8"), "new-stl")

    def test_conflict_skip_leaves_existing_destination_untouched(self):
        (self.input_dir / "DeskClip v2.stl").write_text("new-stl", encoding="utf-8")

        existing = self.output_dir / "DeskClip" / "STLs" / "DeskClip.stl"
        existing.parent.mkdir(parents=True, exist_ok=True)
        existing.write_text("old-stl", encoding="utf-8")

        result = process_exports(
            str(self.input_dir),
            str(self.output_dir),
            allow_overwrite=False,
            conflict_resolver=lambda source, target, operation, keep_both_target: "skip"
        )

        self.assertEqual(result["conflicts_skipped"], 1)
        self.assertEqual(result["skipped_overwrite"], 1)
        self.assertEqual(existing.read_text(encoding="utf-8"), "old-stl")
        self.assertFalse((self.output_dir / "DeskClip" / "STLs" / "DeskClip v2.stl").exists())

    def test_scan_export_conflicts_detects_existing_sorted_target(self):
        (self.input_dir / "DeskClip v2.stl").write_text("new-stl", encoding="utf-8")

        existing = self.output_dir / "DeskClip" / "STLs" / "DeskClip.stl"
        existing.parent.mkdir(parents=True, exist_ok=True)
        existing.write_text("old-stl", encoding="utf-8")

        conflicts = scan_export_conflicts(str(self.input_dir), str(self.output_dir))

        self.assertEqual(len(conflicts), 1)
        self.assertEqual(conflicts[0]["incoming_name"], "DeskClip.stl")
        self.assertEqual(conflicts[0]["existing_name"], "DeskClip.stl")


if __name__ == "__main__":
    unittest.main()
